jobs:
  - name: master
    templates:
      - name: etcd
      - name: kubernetes-master
    instances: 1
    resource_pool: default
    networks:
      - name: default
        static_ips: (( merge ))
    properties:
      networks:
        apps: default
      minion:
        machines: (( merge ))
  - name: minion
    templates:
      - name: docker
      - name: etcd
      - name: flannel
      - name: kubernetes-minion
    instances: 3
    resource_pool: default
    persistent_disk: 65536
    networks:
      - name: default
        static_ips: (( merge ))
    properties:
      networks:
        apps: default
  - name: guestbook-example
    lifecycle: errand
    templates:
      - name: guestbook-example
      - name: etcd
      - name: flannel
    instances: 1
    resource_pool: default
    networks:
      - name: default
        static_ips: (( merge ))
    properties:
      apiserver:
        host: (( static_ips(0) ))
      networks:
        apps: default

properties:
  etcd:
    machines: (( merge ))
  docker: (( merge ))
  
resource_pools: (( merge ))
